name: doc_builder

on:
  push:
    branches:
      - 'master'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: x64
      - name: Install requirements
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Create docs html
        run: |
          cd docs_source
          make html
      - name: Commit changes back to repo
        run: |
          git config --global user.name 'aev-oss-techniscal-user'
          git config --global user.email 'aev-oss-techniscal-user@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.AEV_OSS_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add docs
          git commit -am "automated docs build"
          git push origin
